
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symC {
  /* terminals */
  public static final int WHERE = 13;
  public static final int AND = 14;
  public static final int CADENA = 21;
  public static final int OR = 15;
  public static final int IGUAL = 8;
  public static final int NOT = 16;
  public static final int CORCHCUADI = 9;
  public static final int MENIG = 4;
  public static final int FLECHA = 2;
  public static final int CORCHCUADD = 10;
  public static final int ID = 20;
  public static final int FORM = 18;
  public static final int MEN = 6;
  public static final int NUM = 19;
  public static final int DESIG = 3;
  public static final int COMA = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MAYIG = 5;
  public static final int MAY = 7;
  public static final int PARAM = 22;
  public static final int TO = 17;
  public static final int SELECTT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FLECHA",
  "DESIG",
  "MENIG",
  "MAYIG",
  "MEN",
  "MAY",
  "IGUAL",
  "CORCHCUADI",
  "CORCHCUADD",
  "COMA",
  "SELECTT",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "TO",
  "FORM",
  "NUM",
  "ID",
  "CADENA",
  "PARAM"
  };
}

