// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: LexerResp.jflex

package analizadores;
import java_cup.runtime.*; 
import analizadores.symR.*;
import java.util.List;
import java.util.ArrayList;
import objetos.ErrorCom;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexerResp implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\3\1\1\0\2\1\22\0\1\2\1\3\1\4"+
    "\1\0\1\5\1\0\1\5\1\0\2\5\2\0\1\6"+
    "\2\5\1\0\12\7\1\10\1\0\1\11\1\0\1\12"+
    "\2\0\1\13\1\7\1\14\1\15\1\16\1\7\1\17"+
    "\1\7\1\20\2\7\1\21\1\22\1\23\1\24\1\25"+
    "\1\7\1\26\1\27\1\30\1\31\2\7\1\32\2\7"+
    "\4\0\1\33\1\0\1\34\3\7\1\35\1\36\2\7"+
    "\1\37\4\7\1\40\1\7\1\41\1\7\1\42\1\43"+
    "\1\44\1\45\5\7\1\46\1\5\1\47\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\2\5\1\11\1\12\7\0\2\5\1\13"+
    "\10\0\2\5\33\0\1\14\4\0\1\15\1\0\1\16"+
    "\1\17\5\0\1\20\3\0\1\21\20\0\1\22\1\0"+
    "\1\23\1\24\1\0\1\25\1\26\6\0\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\50\0\170\0\50\0\240\0\50"+
    "\0\50\0\50\0\310\0\360\0\50\0\50\0\u0118\0\u0140"+
    "\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258\0\50"+
    "\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398"+
    "\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0\0\u04d8"+
    "\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618"+
    "\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758"+
    "\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\50\0\u0848\0\u0870"+
    "\0\u0898\0\u08c0\0\50\0\u08e8\0\50\0\50\0\u0910\0\u0938"+
    "\0\u0960\0\u0988\0\u09b0\0\50\0\u09d8\0\u0a00\0\u0a28\0\50"+
    "\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68"+
    "\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\u0c58\0\u0c80\0\u0ca8"+
    "\0\50\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48\0\50\0\50\0\u0d70"+
    "\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\20\7\1\2\2\7\1\13\1\14\6\7"+
    "\1\15\1\16\51\0\2\3\47\0\2\17\1\0\4\17"+
    "\2\0\1\17\1\20\1\21\1\22\2\17\1\23\4\17"+
    "\1\24\1\17\1\25\15\17\11\0\1\7\3\0\20\7"+
    "\1\0\12\7\11\0\1\7\3\0\20\7\1\0\3\7"+
    "\1\26\6\7\11\0\1\7\3\0\20\7\1\0\4\7"+
    "\1\27\5\7\4\0\2\17\1\30\4\17\2\0\33\17"+
    "\4\0\2\17\1\30\4\17\2\0\11\17\1\31\21\17"+
    "\4\0\2\17\1\30\4\17\2\0\3\17\1\32\27\17"+
    "\4\0\2\17\1\30\4\17\2\0\13\17\1\33\17\17"+
    "\4\0\2\17\1\30\4\17\2\0\3\17\1\34\1\17"+
    "\1\35\3\17\1\36\21\17\4\0\2\17\1\30\4\17"+
    "\2\0\3\17\1\37\27\17\4\0\2\17\1\30\4\17"+
    "\2\0\5\17\1\40\25\17\11\0\1\7\3\0\20\7"+
    "\1\0\4\7\1\41\5\7\11\0\1\7\3\0\20\7"+
    "\1\0\3\7\1\42\6\7\4\0\2\17\1\30\4\17"+
    "\2\0\6\17\1\43\24\17\4\0\2\17\1\30\4\17"+
    "\2\0\14\17\1\44\16\17\4\0\2\17\1\30\4\17"+
    "\2\0\13\17\1\45\17\17\4\0\2\17\1\30\4\17"+
    "\2\0\17\17\1\46\13\17\4\0\2\17\1\30\4\17"+
    "\2\0\10\17\1\47\22\17\4\0\2\17\1\30\4\17"+
    "\2\0\4\17\1\50\26\17\4\0\2\17\1\30\4\17"+
    "\2\0\14\17\1\51\16\17\4\0\2\17\1\30\4\17"+
    "\2\0\12\17\1\52\20\17\11\0\1\7\3\0\20\7"+
    "\1\53\12\7\11\0\1\7\3\0\20\7\1\54\12\7"+
    "\4\0\2\17\1\30\4\17\2\0\16\17\1\55\14\17"+
    "\4\0\2\17\1\30\4\17\2\0\1\17\1\56\31\17"+
    "\4\0\2\17\1\30\4\17\2\0\11\17\1\57\21\17"+
    "\4\0\2\17\1\30\4\17\2\0\3\17\1\60\27\17"+
    "\4\0\2\17\1\30\4\17\2\0\3\17\1\61\27\17"+
    "\4\0\2\17\1\30\4\17\2\0\20\17\1\62\12\17"+
    "\4\0\2\17\1\30\4\17\2\0\12\17\1\63\20\17"+
    "\4\0\2\17\1\30\4\17\2\0\11\17\1\64\21\17"+
    "\44\0\1\65\47\0\1\66\7\0\2\17\1\30\4\17"+
    "\2\0\7\17\1\67\23\17\4\0\2\17\1\30\4\17"+
    "\2\0\13\17\1\70\17\17\4\0\2\17\1\30\4\17"+
    "\2\0\13\17\1\71\17\17\4\0\2\17\1\30\4\17"+
    "\2\0\7\17\1\72\23\17\4\0\2\17\1\30\4\17"+
    "\2\0\1\73\32\17\4\0\2\17\1\30\4\17\2\0"+
    "\16\17\1\74\14\17\4\0\2\17\1\30\4\17\2\0"+
    "\16\17\1\75\14\17\4\0\2\17\1\76\4\17\2\0"+
    "\33\17\37\0\1\77\47\0\1\100\14\0\2\17\1\30"+
    "\4\17\2\0\10\17\1\101\22\17\4\0\2\17\1\30"+
    "\4\17\2\0\5\17\1\102\25\17\4\0\2\17\1\103"+
    "\4\17\2\0\33\17\4\0\2\17\1\30\4\17\2\0"+
    "\1\104\32\17\4\0\2\17\1\105\4\17\2\0\33\17"+
    "\4\0\2\17\1\106\4\17\2\0\33\17\4\0\2\17"+
    "\1\30\4\17\2\0\3\17\1\107\27\17\45\0\1\110"+
    "\47\0\1\111\6\0\2\17\1\30\4\17\2\0\1\112"+
    "\32\17\4\0\2\17\1\30\4\17\2\0\12\17\1\113"+
    "\20\17\4\0\2\17\1\114\4\17\2\0\33\17\4\0"+
    "\2\17\1\30\4\17\2\0\14\17\1\115\16\17\43\0"+
    "\1\116\47\0\1\117\10\0\2\17\1\120\4\17\2\0"+
    "\33\17\4\0\2\17\1\30\4\17\2\0\1\17\1\121"+
    "\31\17\4\0\2\17\1\30\4\17\2\0\15\17\1\122"+
    "\15\17\47\0\1\123\47\0\1\124\4\0\2\17\1\30"+
    "\4\17\2\0\5\17\1\125\25\17\4\0\2\17\1\30"+
    "\4\17\2\0\1\126\32\17\37\0\1\127\47\0\1\130"+
    "\14\0\2\17\1\30\4\17\2\0\11\17\1\131\21\17"+
    "\4\0\2\17\1\30\4\17\2\0\20\17\1\132\12\17"+
    "\45\0\1\133\47\0\1\134\6\0\2\17\1\30\4\17"+
    "\2\0\10\17\1\135\22\17\4\0\2\17\1\30\4\17"+
    "\2\0\14\17\1\136\16\17\46\0\1\137\47\0\1\140"+
    "\5\0\2\17\1\141\4\17\2\0\33\17\4\0\2\17"+
    "\1\30\4\17\2\0\11\17\1\142\21\17\36\0\1\143"+
    "\47\0\1\144\15\0\2\17\1\30\4\17\2\0\6\17"+
    "\1\145\24\17\45\0\1\146\47\0\1\147\6\0\2\17"+
    "\1\30\4\17\2\0\5\17\1\150\25\17\4\0\2\17"+
    "\1\30\4\17\2\0\1\17\1\151\31\17\4\0\2\17"+
    "\1\30\4\17\2\0\5\17\1\152\25\17\4\0\2\17"+
    "\1\30\4\17\2\0\15\17\1\153\15\17\4\0\2\17"+
    "\1\30\4\17\2\0\16\17\1\154\14\17\4\0\2\17"+
    "\1\30\4\17\2\0\2\17\1\155\30\17\4\0\2\17"+
    "\1\156\4\17\2\0\33\17\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\1\1\3\11"+
    "\2\1\2\11\7\0\2\1\1\11\10\0\2\1\33\0"+
    "\1\11\4\0\1\11\1\0\2\11\5\0\1\11\3\0"+
    "\1\11\20\0\1\11\1\0\2\1\1\0\2\11\6\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private List<ErrorCom> erroresCom;

    private void error(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","Simbolo no existe en el lenguaje",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }    

    private void errorPalabra(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","Palabra no existe en el lenguaje",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    private void errorNOMP(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","es un nombrep",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    private void errorNOMO(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","es un nombreopciones",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    private void errorID(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","es un ID",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    private void errorFINS(String lexeme) {
        erroresCom.add(new ErrorCom("Lexico","es un fin sols",String.valueOf(yyline+1),String.valueOf(yycolumn+1),lexeme));
    }

    public List<ErrorCom> getErroresCom() {
        return erroresCom;
    }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerResp(java.io.Reader in) {
      erroresCom = new ArrayList<>();
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext()); new Symbol(symF.error,yyline,yycolumn, yytext());
            }
            // fall through
          case 24: break;
          case 2:
            { 
            }
            // fall through
          case 25: break;
          case 3:
            { return new Symbol(symR.EXCL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 26: break;
          case 4:
            { return new Symbol(symR.COMA,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 27: break;
          case 5:
            { errorPalabra(yytext());
            }
            // fall through
          case 28: break;
          case 6:
            { return new Symbol(symR.DOSPUNT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 29: break;
          case 7:
            { return new Symbol(symR.MEN,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 30: break;
          case 8:
            { return new Symbol(symR.MAY,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 31: break;
          case 9:
            { return new Symbol(symR.CORCHI,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 32: break;
          case 10:
            { return new Symbol(symR.CORCHD,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 33: break;
          case 11:
            { return new Symbol(symR.CONT,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 34: break;
          case 12:
            { return new Symbol(symR.TIPO,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 35: break;
          case 13:
            { return new Symbol(symR.ERR,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 36: break;
          case 14:
            { return new Symbol(symR.LIN,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 37: break;
          case 15:
            { return new Symbol(symR.LOGU,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 38: break;
          case 16:
            { return new Symbol(symR.LEX,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 39: break;
          case 17:
            { return new Symbol(symR.COL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 40: break;
          case 18:
            { return new Symbol(symR.DESC,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 41: break;
          case 19:
            { return new Symbol(symR.FIN_RESP,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 42: break;
          case 20:
            { return new Symbol(symR.INI_RESP,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 43: break;
          case 21:
            { return new Symbol(symR.FIN_RESPS,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 44: break;
          case 22:
            { return new Symbol(symR.INI_RESPS,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 45: break;
          case 23:
            { return new Symbol(symR.SOL,yyline+1,yycolumn+1, yytext());
            }
            // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexerResp [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexerResp scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexerResp(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
