
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symR {
  /* terminals */
  public static final int DOSPUNT = 2;
  public static final int DESC = 16;
  public static final int EXCL = 8;
  public static final int SOL = 14;
  public static final int LIN = 17;
  public static final int COL = 18;
  public static final int ERR = 13;
  public static final int LOGU = 20;
  public static final int MEN = 7;
  public static final int CONT = 21;
  public static final int FIN_RESPS = 11;
  public static final int TIPO = 15;
  public static final int COMA = 5;
  public static final int CORCHI = 3;
  public static final int EOF = 0;
  public static final int CORCHD = 4;
  public static final int LEX = 19;
  public static final int INI_RESPS = 9;
  public static final int FIN_RESP = 12;
  public static final int error = 1;
  public static final int INI_RESP = 10;
  public static final int MAY = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNT",
  "CORCHI",
  "CORCHD",
  "COMA",
  "MAY",
  "MEN",
  "EXCL",
  "INI_RESPS",
  "INI_RESP",
  "FIN_RESPS",
  "FIN_RESP",
  "ERR",
  "SOL",
  "TIPO",
  "DESC",
  "LIN",
  "COL",
  "LEX",
  "LOGU",
  "CONT"
  };
}

