
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symF {
  /* terminals */
  public static final int FORM = 19;
  public static final int BOTON = 42;
  public static final int REQUE = 27;
  public static final int CHECK_BOX = 37;
  public static final int ESTRUCT = 21;
  public static final int NOMBRE = 13;
  public static final int NOMBREP = 9;
  public static final int WHITE = 34;
  public static final int IZQUIERDA = 44;
  public static final int INDICE = 24;
  public static final int ID_FORM = 20;
  public static final int INI = 8;
  public static final int CENTRO = 43;
  public static final int NOMBRE_OPCION = 10;
  public static final int ID = 11;
  public static final int ALINEA = 26;
  public static final int FICHERO = 39;
  public static final int TEXTO_VIS = 25;
  public static final int CAMPO_TEXT = 35;
  public static final int EOF = 0;
  public static final int CLASE = 23;
  public static final int error = 1;
  public static final int USUARIO_CREA = 15;
  public static final int COMA = 5;
  public static final int CORCHI = 3;
  public static final int URL = 31;
  public static final int CORCHD = 4;
  public static final int NOMBRE_COMP = 22;
  public static final int ID_COMP = 17;
  public static final int TEMA = 14;
  public static final int FECHA_CREA = 16;
  public static final int RADIO = 38;
  public static final int TITUL = 12;
  public static final int AREA_TEXT = 36;
  public static final int DERECHA = 45;
  public static final int IMAGEN = 40;
  public static final int NOMBRE_CAMPO = 18;
  public static final int PARI = 6;
  public static final int COMBO = 41;
  public static final int BLUE = 32;
  public static final int DARK = 33;
  public static final int PARD = 7;
  public static final int DOSPUNT = 2;
  public static final int COLUMNAS = 30;
  public static final int JUSTIFICAR = 46;
  public static final int FILAS = 29;
  public static final int OPCIONES = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNT",
  "CORCHI",
  "CORCHD",
  "COMA",
  "PARI",
  "PARD",
  "INI",
  "NOMBREP",
  "NOMBRE_OPCION",
  "ID",
  "TITUL",
  "NOMBRE",
  "TEMA",
  "USUARIO_CREA",
  "FECHA_CREA",
  "ID_COMP",
  "NOMBRE_CAMPO",
  "FORM",
  "ID_FORM",
  "ESTRUCT",
  "NOMBRE_COMP",
  "CLASE",
  "INDICE",
  "TEXTO_VIS",
  "ALINEA",
  "REQUE",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URL",
  "BLUE",
  "DARK",
  "WHITE",
  "CAMPO_TEXT",
  "AREA_TEXT",
  "CHECK_BOX",
  "RADIO",
  "FICHERO",
  "IMAGEN",
  "COMBO",
  "BOTON",
  "CENTRO",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR"
  };
}

