
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import objetos.ErrorCom;
import objetos.Solicitud;
import objetos.Parametro;
import objetos.ControlSemantico;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserIndigo extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserIndigo() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserIndigo(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserIndigo(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\166\000\002\002\004\000\002\002\005\000\002\003" +
    "\005\000\002\003\005\000\002\004\007\000\002\004\006" +
    "\000\002\004\002\000\002\040\002\000\002\005\007\000" +
    "\002\041\002\000\002\005\007\000\002\042\002\000\002" +
    "\005\007\000\002\043\002\000\002\005\007\000\002\044" +
    "\002\000\002\005\007\000\002\045\002\000\002\005\007" +
    "\000\002\046\002\000\002\005\007\000\002\047\002\000" +
    "\002\005\007\000\002\050\002\000\002\005\007\000\002" +
    "\051\002\000\002\005\007\000\002\005\005\000\002\006" +
    "\007\000\002\007\007\000\002\010\007\000\002\011\007" +
    "\000\002\012\007\000\002\052\002\000\002\013\006\000" +
    "\002\053\002\000\002\013\006\000\002\013\004\000\002" +
    "\013\004\000\002\054\002\000\002\014\006\000\002\055" +
    "\002\000\002\014\006\000\002\056\002\000\002\014\006" +
    "\000\002\057\002\000\002\014\006\000\002\060\002\000" +
    "\002\015\011\000\002\061\002\000\002\016\006\000\002" +
    "\062\002\000\002\016\006\000\002\063\002\000\002\016" +
    "\006\000\002\064\002\000\002\016\006\000\002\065\002" +
    "\000\002\016\006\000\002\022\003\000\002\023\003\000" +
    "\002\023\003\000\002\066\002\000\002\017\011\000\002" +
    "\067\002\000\002\020\006\000\002\070\002\000\002\020" +
    "\006\000\002\071\002\000\002\020\006\000\002\072\002" +
    "\000\002\021\006\000\002\073\002\000\002\021\006\000" +
    "\002\074\002\000\002\021\006\000\002\075\002\000\002" +
    "\021\006\000\002\076\002\000\002\021\006\000\002\077" +
    "\002\000\002\021\006\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003\000\002\025\004\000\002" +
    "\026\004\000\002\034\004\000\002\034\004\000\002\034" +
    "\004\000\002\034\004\000\002\034\004\000\002\034\004" +
    "\000\002\034\004\000\002\034\004\000\002\035\004\000" +
    "\002\035\004\000\002\035\004\000\002\035\004\000\002" +
    "\036\004\000\002\036\003\000\002\037\004\000\002\037" +
    "\004\000\002\037\004\000\002\027\004\000\002\027\006" +
    "\000\002\030\004\000\002\030\006\000\002\031\004\000" +
    "\002\031\006\000\002\032\004\000\002\032\006\000\002" +
    "\033\004\000\002\033\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0103\000\004\006\004\001\002\000\004\005\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\006\021\010\022\011\001\002\000\004\004\u0104\001" +
    "\002\000\004\007\013\001\002\000\004\002\000\001\002" +
    "\000\006\002\ufffb\006\014\001\002\000\004\005\016\001" +
    "\002\000\004\002\uffff\001\002\000\006\021\017\024\020" +
    "\001\002\000\004\004\022\001\002\000\004\007\021\001" +
    "\002\000\004\002\ufffc\001\002\000\030\034\032\035\034" +
    "\036\026\037\031\040\036\041\023\042\033\043\024\044" +
    "\030\045\025\046\027\001\002\000\004\007\u0100\001\002" +
    "\000\004\007\374\001\002\000\004\007\302\001\002\000" +
    "\004\007\267\001\002\000\004\007\260\001\002\000\004" +
    "\007\240\001\002\000\004\007\234\001\002\000\004\007" +
    "\207\001\002\000\004\007\161\001\002\000\004\007\122" +
    "\001\002\000\004\002\ufffd\001\002\000\004\007\037\001" +
    "\002\000\004\010\041\001\002\000\016\055\ufff2\056\ufff2" +
    "\057\ufff2\060\ufff2\061\ufff2\062\ufff2\001\002\000\004\031" +
    "\042\001\002\000\004\004\043\001\002\000\004\012\044" +
    "\001\002\000\004\010\045\001\002\000\016\055\uffe3\056" +
    "\uffe3\057\uffe3\060\uffe3\061\uffe3\062\uffe3\001\002\000\016" +
    "\055\050\056\056\057\052\060\055\061\054\062\047\001" +
    "\002\000\004\004\060\001\002\000\004\004\uffc5\001\002" +
    "\000\004\004\uffc6\001\002\000\004\004\110\001\002\000" +
    "\004\004\101\001\002\000\004\004\101\001\002\000\004" +
    "\004\060\001\002\000\004\004\uffc4\001\002\000\004\002" +
    "\ufff1\001\002\000\004\027\077\001\002\000\006\011\uffca" +
    "\017\uffca\001\002\000\006\011\064\017\063\001\002\000" +
    "\016\055\050\056\056\057\052\060\055\061\054\062\047" +
    "\001\002\000\004\013\066\001\002\000\004\002\uffc9\001" +
    "\002\000\004\011\067\001\002\000\004\006\070\001\002" +
    "\000\004\023\072\001\002\000\004\002\uff90\001\002\000" +
    "\004\005\073\001\002\000\004\007\074\001\002\000\006" +
    "\002\ufffb\006\014\001\002\000\004\002\uffe5\001\002\000" +
    "\004\002\uff91\001\002\000\006\011\uffa7\017\uffa7\001\002" +
    "\000\006\011\uffc8\017\uffc8\001\002\000\004\025\102\001" +
    "\002\000\006\011\uffa8\017\uffa8\001\002\000\006\011\064" +
    "\017\063\001\002\000\004\002\uffc7\001\002\000\006\011" +
    "\uffd0\017\uffd0\001\002\000\006\011\064\017\063\001\002" +
    "\000\004\002\uffcf\001\002\000\010\076\115\077\116\100" +
    "\114\001\002\000\006\011\uffcc\017\uffcc\001\002\000\006" +
    "\011\064\017\063\001\002\000\004\002\uffcb\001\002\000" +
    "\006\011\uff96\017\uff96\001\002\000\006\011\uff97\017\uff97" +
    "\001\002\000\006\011\uff98\017\uff98\001\002\000\006\011" +
    "\uffce\017\uffce\001\002\000\006\011\064\017\063\001\002" +
    "\000\004\002\uffcd\001\002\000\004\010\124\001\002\000" +
    "\012\051\ufff8\052\ufff8\053\ufff8\054\ufff8\001\002\000\004" +
    "\030\125\001\002\000\004\004\126\001\002\000\004\012" +
    "\127\001\002\000\004\010\130\001\002\000\020\003\uffe4" +
    "\047\uffe4\050\uffe4\051\uffe4\052\uffe4\053\uffe4\054\uffe4\001" +
    "\002\000\012\051\133\052\134\053\136\054\135\001\002" +
    "\000\004\002\ufff7\001\002\000\004\004\101\001\002\000" +
    "\004\004\101\001\002\000\004\004\101\001\002\000\004" +
    "\004\101\001\002\000\006\011\uffd6\017\uffd6\001\002\000" +
    "\006\011\142\017\141\001\002\000\012\051\133\052\134" +
    "\053\136\054\135\001\002\000\004\013\144\001\002\000" +
    "\004\002\uffd5\001\002\000\004\011\145\001\002\000\004" +
    "\006\070\001\002\000\004\002\uff92\001\002\000\004\002" +
    "\uff93\001\002\000\006\011\uffd4\017\uffd4\001\002\000\006" +
    "\011\142\017\141\001\002\000\004\002\uffd3\001\002\000" +
    "\006\011\uffd8\017\uffd8\001\002\000\006\011\142\017\141" +
    "\001\002\000\004\002\uffd7\001\002\000\006\011\uffda\017" +
    "\uffda\001\002\000\006\011\142\017\141\001\002\000\004" +
    "\002\uffd9\001\002\000\004\010\041\001\002\000\012\055" +
    "\uffee\056\uffee\057\uffee\062\uffee\001\002\000\012\055\050" +
    "\056\056\057\164\062\165\001\002\000\004\004\110\001" +
    "\002\000\004\004\060\001\002\000\004\004\101\001\002" +
    "\000\004\002\uffed\001\002\000\006\011\uffc1\017\uffc1\001" +
    "\002\000\006\011\174\017\172\001\002\000\012\055\050" +
    "\056\056\057\164\062\165\001\002\000\004\002\uffc0\001" +
    "\002\000\004\013\175\001\002\000\004\011\176\001\002" +
    "\000\004\006\070\001\002\000\004\002\uff8e\001\002\000" +
    "\004\002\uff8f\001\002\000\006\011\uffbd\017\uffbd\001\002" +
    "\000\006\011\174\017\172\001\002\000\004\002\uffbc\001" +
    "\002\000\006\011\uffbf\017\uffbf\001\002\000\006\011\174" +
    "\017\172\001\002\000\004\002\uffbe\001\002\000\004\010" +
    "\124\001\002\000\010\003\ufffa\047\ufffa\050\ufffa\001\002" +
    "\000\010\003\214\047\213\050\212\001\002\000\004\004" +
    "\101\001\002\000\004\004\101\001\002\000\014\003\214" +
    "\011\217\017\216\047\213\050\212\001\002\000\004\002" +
    "\ufff9\001\002\000\010\003\214\047\213\050\212\001\002" +
    "\000\004\013\222\001\002\000\004\002\uffdc\001\002\000" +
    "\004\002\uffdb\001\002\000\004\011\223\001\002\000\004" +
    "\006\070\001\002\000\004\002\uff94\001\002\000\004\002" +
    "\uff95\001\002\000\006\011\uffe0\017\uffe0\001\002\000\006" +
    "\011\217\017\216\001\002\000\004\002\uffdf\001\002\000" +
    "\006\011\uffde\017\uffde\001\002\000\006\011\217\017\216" +
    "\001\002\000\004\002\uffdd\001\002\000\004\010\124\001" +
    "\002\000\010\003\ufff4\047\ufff4\050\ufff4\001\002\000\010" +
    "\003\214\047\213\050\212\001\002\000\004\002\ufff3\001" +
    "\002\000\004\010\242\001\002\000\004\062\uffea\001\002" +
    "\000\004\032\243\001\002\000\004\004\244\001\002\000" +
    "\004\012\245\001\002\000\004\010\246\001\002\000\032" +
    "\062\uffe2\063\uffe2\064\uffe2\065\uffe2\066\uffe2\067\uffe2\070" +
    "\uffe2\071\uffe2\072\uffe2\073\uffe2\074\uffe2\075\uffe2\001\002" +
    "\000\004\062\251\001\002\000\004\002\uffe9\001\002\000" +
    "\004\004\060\001\002\000\004\011\uffc3\001\002\000\004" +
    "\011\254\001\002\000\004\013\255\001\002\000\004\011" +
    "\256\001\002\000\004\006\070\001\002\000\004\002\uffc2" +
    "\001\002\000\004\010\262\001\002\000\004\002\uffe6\001" +
    "\002\000\004\033\263\001\002\000\004\004\264\001\002" +
    "\000\004\012\265\001\002\000\004\010\266\001\002\000" +
    "\004\002\uffe1\001\002\000\004\010\124\001\002\000\004" +
    "\047\ufff6\001\002\000\004\047\273\001\002\000\004\002" +
    "\ufff5\001\002\000\004\004\101\001\002\000\004\011\uffd2" +
    "\001\002\000\004\011\276\001\002\000\004\013\277\001" +
    "\002\000\004\011\300\001\002\000\004\006\070\001\002" +
    "\000\004\002\uffd1\001\002\000\004\010\242\001\002\000" +
    "\032\062\uffe8\063\uffe8\064\uffe8\065\uffe8\066\uffe8\067\uffe8" +
    "\070\uffe8\071\uffe8\072\uffe8\073\uffe8\074\uffe8\075\uffe8\001" +
    "\002\000\032\062\306\063\307\064\305\065\317\066\316" +
    "\067\313\070\312\071\322\072\311\073\310\074\315\075" +
    "\320\001\002\000\004\004\060\001\002\000\004\004\060" +
    "\001\002\000\004\004\uffaf\001\002\000\004\004\uffab\001" +
    "\002\000\004\004\361\001\002\000\004\004\350\001\002" +
    "\000\004\004\uffad\001\002\000\004\004\101\001\002\000" +
    "\004\004\uffaa\001\002\000\004\004\uffae\001\002\000\004" +
    "\004\323\001\002\000\004\004\uffa9\001\002\000\004\002" +
    "\uffe7\001\002\000\004\004\uffac\001\002\000\022\101\343" +
    "\102\336\103\341\104\337\105\344\106\340\107\342\110" +
    "\335\001\002\000\006\011\uffb9\017\uffb9\001\002\000\006" +
    "\011\327\017\326\001\002\000\032\062\306\063\307\064" +
    "\305\065\317\066\316\067\313\070\312\071\322\072\311" +
    "\073\310\074\315\075\320\001\002\000\004\013\331\001" +
    "\002\000\004\002\uffb8\001\002\000\004\011\332\001\002" +
    "\000\004\006\070\001\002\000\004\002\uff8c\001\002\000" +
    "\004\002\uff8d\001\002\000\006\011\uff9f\017\uff9f\001\002" +
    "\000\006\011\uffa5\017\uffa5\001\002\000\006\011\uffa3\017" +
    "\uffa3\001\002\000\006\011\uffa1\017\uffa1\001\002\000\006" +
    "\011\uffa4\017\uffa4\001\002\000\006\011\uffa0\017\uffa0\001" +
    "\002\000\006\011\uffa6\017\uffa6\001\002\000\006\011\uffa2" +
    "\017\uffa2\001\002\000\006\011\uffbb\017\uffbb\001\002\000" +
    "\006\011\327\017\326\001\002\000\004\002\uffba\001\002" +
    "\000\012\111\356\112\355\113\354\114\357\001\002\000" +
    "\006\011\uffb7\017\uffb7\001\002\000\006\011\327\017\326" +
    "\001\002\000\004\002\uffb6\001\002\000\006\011\uff9c\017" +
    "\uff9c\001\002\000\006\011\uff9d\017\uff9d\001\002\000\006" +
    "\011\uff9e\017\uff9e\001\002\000\006\011\uff9b\017\uff9b\001" +
    "\002\000\006\011\uff99\017\uff99\001\002\000\006\025\102" +
    "\026\365\001\002\000\006\011\uffb5\017\uffb5\001\002\000" +
    "\006\011\327\017\326\001\002\000\004\002\uffb4\001\002" +
    "\000\006\011\uff9a\017\uff9a\001\002\000\006\011\uffb3\017" +
    "\uffb3\001\002\000\006\011\327\017\326\001\002\000\004" +
    "\002\uffb2\001\002\000\006\011\uffb1\017\uffb1\001\002\000" +
    "\006\011\327\017\326\001\002\000\004\002\uffb0\001\002" +
    "\000\004\010\242\001\002\000\032\062\uffec\063\uffec\064" +
    "\uffec\065\uffec\066\uffec\067\uffec\070\uffec\071\uffec\072\uffec" +
    "\073\uffec\074\uffec\075\uffec\001\002\000\032\062\306\063" +
    "\307\064\305\065\317\066\316\067\313\070\312\071\322" +
    "\072\311\073\310\074\315\075\320\001\002\000\004\002" +
    "\uffeb\001\002\000\004\010\041\001\002\000\004\062\ufff0" +
    "\001\002\000\004\062\251\001\002\000\004\002\uffef\001" +
    "\002\000\030\034\032\035\034\036\026\037\031\040\036" +
    "\041\023\042\033\043\024\044\030\045\025\046\027\001" +
    "\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0103\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\011\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\014\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\037\001\001\000\004" +
    "\044\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\016\056\022\052\023\050\001\001\000\004\026\116\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\037\110" +
    "\001\001\000\004\025\104\001\001\000\004\025\077\001" +
    "\001\000\004\026\060\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\064\061\001\001\000" +
    "\004\031\064\001\001\000\010\016\075\022\052\023\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\070\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\074\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\065\102\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\031\103\001\001\000\002\001\001" +
    "\000\004\061\105\001\001\000\004\031\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\063\111\001\001" +
    "\000\004\031\112\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\062\117" +
    "\001\001\000\004\031\120\001\001\000\002\001\001\000" +
    "\004\007\122\001\001\000\004\041\130\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\014\131\001\001\000\002" +
    "\001\001\000\004\025\155\001\001\000\004\025\152\001" +
    "\001\000\004\025\147\001\001\000\004\025\136\001\001" +
    "\000\004\056\137\001\001\000\004\030\142\001\001\000" +
    "\004\014\146\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\145\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\057\150\001\001\000\004" +
    "\030\151\001\001\000\002\001\001\000\004\055\153\001" +
    "\001\000\004\030\154\001\001\000\002\001\001\000\004" +
    "\054\156\001\001\000\004\030\157\001\001\000\002\001" +
    "\001\000\004\010\161\001\001\000\004\046\162\001\001" +
    "\000\006\020\166\023\165\001\001\000\004\037\203\001" +
    "\001\000\004\026\200\001\001\000\004\025\167\001\001" +
    "\000\002\001\001\000\004\067\170\001\001\000\004\032" +
    "\172\001\001\000\006\020\177\023\165\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\176\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\071\201\001\001\000\004\032\202\001\001\000\002\001" +
    "\001\000\004\070\204\001\001\000\004\032\205\001\001" +
    "\000\002\001\001\000\004\007\207\001\001\000\004\040" +
    "\210\001\001\000\004\013\214\001\001\000\004\025\230" +
    "\001\001\000\004\025\225\001\001\000\006\013\217\027" +
    "\220\001\001\000\002\001\001\000\004\013\224\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\006\223\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\052\226\001\001\000\004\027" +
    "\227\001\001\000\002\001\001\000\004\053\231\001\001" +
    "\000\004\027\232\001\001\000\002\001\001\000\004\007" +
    "\234\001\001\000\004\043\235\001\001\000\004\013\236" +
    "\001\001\000\002\001\001\000\004\011\240\001\001\000" +
    "\004\050\246\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\017\247\001\001\000\002\001\001\000\004\026\251" +
    "\001\001\000\004\066\252\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\006\256\001\001" +
    "\000\002\001\001\000\004\012\260\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\267\001" +
    "\001\000\004\042\270\001\001\000\004\015\271\001\001" +
    "\000\002\001\001\000\004\025\273\001\001\000\004\060" +
    "\274\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\300\001\001\000\002\001\001\000" +
    "\004\011\302\001\001\000\004\051\303\001\001\000\006" +
    "\021\320\024\313\001\001\000\004\026\370\001\001\000" +
    "\004\026\365\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\025\357\036\361\001\001\000\004\035\350\001" +
    "\001\000\002\001\001\000\004\025\344\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\034\323\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\073\324\001\001\000\004\033\327\001" +
    "\001\000\006\021\333\024\313\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\332\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\072\345\001\001\000\004\033\346\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\074\351" +
    "\001\001\000\004\033\352\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\075" +
    "\362\001\001\000\004\033\363\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\076\366\001\001\000\004\033" +
    "\367\001\001\000\002\001\001\000\004\077\371\001\001" +
    "\000\004\033\372\001\001\000\002\001\001\000\004\011" +
    "\374\001\001\000\004\047\375\001\001\000\006\021\376" +
    "\024\313\001\001\000\002\001\001\000\004\010\u0100\001" +
    "\001\000\004\045\u0101\001\001\000\004\017\u0102\001\001" +
    "\000\002\001\001\000\004\005\u0104\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserIndigo$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserIndigo$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserIndigo$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private List<ErrorCom> erroresCom;
    private List<Solicitud> solicitudes;
    private Solicitud solicitudAct; 
    private Parametro parametroAct; 

	public ParserIndigo(LexerIndigo lex) {
		super(lex);
        this.erroresCom = lex.getErroresCom();
        this.solicitudes = new ArrayList<>();
        crearSolicitud();
	}

    /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s){ 
        erroresCom.add(new ErrorCom("Sintactico","No se esperaba Componente",String.valueOf(s.left),String.valueOf(s.right),String.valueOf(s.value)));
    } 

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        erroresCom.add(new ErrorCom("Sintactico","Error sintactico Irrecuperable",String.valueOf(s.left),String.valueOf(s.right),String.valueOf(s.value)));
    } 

    private void setParam(String nombreParam,String lin,String col){
        crearSolicitud();
        solicitudAct.setTipo(nombreParam);         
        solicitudAct.setLin(lin);
        solicitudAct.setCol(col);
        setNuevaSolicitud();
    }

    private void crearSolicitud(){
        solicitudAct = new Solicitud();
    }

    private void setNuevaSolicitud(){
        this.solicitudes.add(solicitudAct);
    }

    protected int error_sync_size() {
		return 2;
	}

    public List<ErrorCom> getErroresCom(){
        return erroresCom;
    }

    public List<Solicitud> getSolicitudes(){
        return solicitudes;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserIndigo$actions {
  private final ParserIndigo parser;

  /** Constructor */
  CUP$ParserIndigo$actions(ParserIndigo parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserIndigo$do_action_part00000000(
    int                        CUP$ParserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$ParserIndigo$parser,
    java.util.Stack            CUP$ParserIndigo$stack,
    int                        CUP$ParserIndigo$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserIndigo$result;

      /* select the action based on the action number */
      switch (CUP$ParserIndigo$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		RESULT = start_val;
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserIndigo$parser.done_parsing();
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= MEN EXCL inicio2 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio2 ::= INISOLS MAY sig 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("inicio2",1, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio2 ::= INISOL DOSPUNT sig2 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("inicio2",1, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sig ::= MEN EXCL INISOL DOSPUNT sig2 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig",2, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sig ::= MEN EXCL FINSOLS MAY 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig",2, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sig ::= 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig",2, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$0 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("CREAR_U", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$0",30, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sig2 ::= CREAR_U MAY sig4 NT$0 par1 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$1 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("MOD_U", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$1",31, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sig2 ::= MOD_U MAY sig4 NT$1 par2 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$2 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("ELIM_U", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$2",32, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sig2 ::= ELIM_U MAY sig4 NT$2 par3 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$3 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("LOG_U", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$3",33, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sig2 ::= LOG_U MAY sig4 NT$3 par1 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$4 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("NUEVO_FORM", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$4",34, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sig2 ::= NUEVO_FORM MAY sig5 NT$4 par4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$5 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("ELIM_FORM", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$5",35, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sig2 ::= ELIM_FORM MAY sig5 NT$5 par5 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$6 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("MOD_FORM", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$6",36, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sig2 ::= MOD_FORM MAY sig5 NT$6 par6 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$7 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("AGRE_COMP", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$7",37, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sig2 ::= AGRE_COMP MAY sig6 NT$7 par7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$8 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("ELIM_COMP", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$8",38, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sig2 ::= ELIM_COMP MAY sig6 NT$8 par5 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$9 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
setParam("MOD_COMP", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$9",39, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sig2 ::= MOD_COMP MAY sig6 NT$9 par7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sig2 ::= CONSULT MAY sig7 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;
		setParam("CONSULT", String.valueOf(sleft),String.valueOf(sright));
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig2",3, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sig3 ::= MEN FINSOL EXCL MAY sig 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig3",4, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sig4 ::= CORCHI CREDEN_U DOSPUNT CORCHCUADI CORCHI 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig4",5, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sig5 ::= CORCHI PARAMS_FORM DOSPUNT CORCHCUADI CORCHI 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig5",6, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sig6 ::= CORCHI PARAMS_COMP DOSPUNT CORCHCUADI CORCHI 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig6",7, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sig7 ::= CORCHI CONSULTS DOSPUNT CORCHCUADI CORCHI 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("sig7",8, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NT$10 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
parametroAct.setNombre("USUARIO");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$10",40, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // par1 ::= USUARIO nomP NT$10 fin1 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par1",9, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NT$11 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
 parametroAct.setNombre("PASS");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$11",41, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // par1 ::= PASS nomP NT$11 fin1 
            {
              Object RESULT =null;
              // propagate RESULT from NT$11
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par1",9, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // par1 ::= error par1 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par1",9, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // par1 ::= error fin1 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par1",9, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$12 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
 parametroAct.setNombre("USUARIO_ANTI");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$12",42, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // par2 ::= USUARIO_ANTI nomP NT$12 fin2 
            {
              Object RESULT =null;
              // propagate RESULT from NT$12
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par2",10, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$13 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
 parametroAct.setNombre("USUARIO_NUEVO");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$13",43, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // par2 ::= USUARIO_NUEVO nomP NT$13 fin2 
            {
              Object RESULT =null;
              // propagate RESULT from NT$13
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par2",10, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // NT$14 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
 parametroAct.setNombre("NUEVO_PASS");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$14",44, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // par2 ::= NUEVO_PASS nomP NT$14 fin2 
            {
              Object RESULT =null;
              // propagate RESULT from NT$14
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par2",10, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // NT$15 ::= 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
 parametroAct.setNombre("FECHA_MOD");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$15",45, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // par2 ::= FECHA_MOD nomP NT$15 fin2 
            {
              Object RESULT =null;
              // propagate RESULT from NT$15
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).right;
		Object nom = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-2)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par2",10, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // NT$16 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("USUARIO");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$16",46, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // par3 ::= USUARIO nomP NT$16 CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;
              // propagate RESULT from NT$16
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par3",11, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-6)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // NT$17 ::= 
            {
              Object RESULT =null;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
 parametroAct.setNombre(String.valueOf(par));solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$17",47, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // par4 ::= parp4 nomP NT$17 fin4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$17
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par4",12, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // NT$18 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("ID");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$18",48, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // par4 ::= ID2 nomp2 NT$18 fin4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$18
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par4",12, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // NT$19 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("TEMA");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$19",49, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // par4 ::= TEMA np4 NT$19 fin4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$19
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par4",12, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // NT$20 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("USUARIO_CREA");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$20",50, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // par4 ::= USUARIO_CREA nomp2 NT$20 fin4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$20
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par4",12, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // NT$21 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("FECHA_CREA");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$21",51, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // par4 ::= FECHA_CREA nomP NT$21 fin4 
            {
              Object RESULT =null;
              // propagate RESULT from NT$21
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par4",12, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // parp4 ::= parpp4 
            {
              Object RESULT =null;
		int parpleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int parpright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		Object parp = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
		RESULT = String.valueOf(parp);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp4",16, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // parpp4 ::= TITUL 
            {
              Object RESULT =null;
		 RESULT = "TITUL"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parpp4",17, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // parpp4 ::= NOMBRE 
            {
              Object RESULT =null;
		 RESULT = "NOMBRE"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parpp4",17, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // NT$22 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("ID");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$22",52, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // par5 ::= ID2 nomp2 NT$22 CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;
              // propagate RESULT from NT$22
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-4)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par5",13, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-6)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // NT$23 ::= 
            {
              Object RESULT =null;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
 parametroAct.setNombre(String.valueOf(par));solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$23",53, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // par6 ::= parpp4 nomP NT$23 fin6 
            {
              Object RESULT =null;
              // propagate RESULT from NT$23
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par6",14, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // NT$24 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("TEMA");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$24",54, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // par6 ::= TEMA np4 NT$24 fin6 
            {
              Object RESULT =null;
              // propagate RESULT from NT$24
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par6",14, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // NT$25 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("ID");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$25",55, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // par6 ::= ID2 nomp2 NT$25 fin6 
            {
              Object RESULT =null;
              // propagate RESULT from NT$25
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par6",14, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // NT$26 ::= 
            {
              Object RESULT =null;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
 parametroAct.setNombre(String.valueOf(par));solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$26",56, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // par7 ::= parp7 nomP NT$26 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$26
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;
		int parleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).left;
		int parright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).right;
		Object par = (Object)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // NT$27 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("CLASE");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$27",57, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // par7 ::= CLASE np1 NT$27 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$27
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // NT$28 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("ALINEA");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$28",58, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // par7 ::= ALINEA np2 NT$28 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$28
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // NT$29 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("OPCIONES");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$29",59, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // par7 ::= OPCIONES np3 NT$29 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$29
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // NT$30 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("ID");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$30",60, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // par7 ::= ID2 nomp2 NT$30 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$30
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // NT$31 ::= 
            {
              Object RESULT =null;
 parametroAct.setNombre("FORM");solicitudAct.setNewParametro(parametroAct);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("NT$31",61, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // par7 ::= FORM nomp2 NT$31 fin7 
            {
              Object RESULT =null;
              // propagate RESULT from NT$31
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)).value;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("par7",15, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // parp7 ::= NOMBRE_CAMPO 
            {
              Object RESULT =null;
		 RESULT = "NOMBRE_CAMPO"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // parp7 ::= INDICE 
            {
              Object RESULT =null;
		 RESULT = "INDICE"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // parp7 ::= TEXTO_VIS 
            {
              Object RESULT =null;
		 RESULT = "TEXTO_VIS"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // parp7 ::= REQUE 
            {
              Object RESULT =null;
		 RESULT = "REQUE"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // parp7 ::= FILAS 
            {
              Object RESULT =null;
		 RESULT = "FILAS"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // parp7 ::= COLUMNAS 
            {
              Object RESULT =null;
		 RESULT = "COLUMNAS"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // parp7 ::= URL 
            {
              Object RESULT =null;
		 RESULT = "URL"; 
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("parp7",18, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // nomP ::= DOSPUNT NOMBREP 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
		parametroAct = new Parametro();parametroAct.setContenido(nom);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("nomP",19, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // nomp2 ::= DOSPUNT ID 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
		parametroAct = new Parametro();parametroAct.setContenido(nom);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("nomp2",20, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // np1 ::= DOSPUNT CAMPO_TEXT 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("CAMPO_TEXT");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // np1 ::= DOSPUNT AREA_TEXT 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("AREA_TEXT");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // np1 ::= DOSPUNT CHECK_BOX 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("CHECK_BOX");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // np1 ::= DOSPUNT RADIO 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("RADIO");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // np1 ::= DOSPUNT FICHERO 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("FICHERO");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // np1 ::= DOSPUNT IMAGEN 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("IMAGEN");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // np1 ::= DOSPUNT COMBO 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("COMBO");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // np1 ::= DOSPUNT BOTON 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("BOTON");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np1",26, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // np2 ::= DOSPUNT CENTRO 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("CENTRO");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np2",27, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // np2 ::= DOSPUNT IZQUIERDA 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("IZQUIERDA");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np2",27, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // np2 ::= DOSPUNT DERECHA 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("DERECHA");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np2",27, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // np2 ::= DOSPUNT JUSTIFICAR 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("JUSTIFICAR");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np2",27, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // np3 ::= DOSPUNT NOMBRE_OPCION 
            {
              Object RESULT =null;
		int nomOPleft = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).left;
		int nomOPright = ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()).right;
		String nomOP = (String)((java_cup.runtime.Symbol) CUP$ParserIndigo$stack.peek()).value;
		parametroAct = new Parametro();parametroAct.setContenido(nomOP);
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np3",28, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // np3 ::= nomP 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np3",28, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // np4 ::= DOSPUNT DARK 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("DARK");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np4",29, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // np4 ::= DOSPUNT BLUE 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("BLUE");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np4",29, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // np4 ::= DOSPUNT WHITE 
            {
              Object RESULT =null;
		parametroAct = new Parametro();parametroAct.setContenido("WHITE");
              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("np4",29, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // fin1 ::= COMA par1 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin1",21, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // fin1 ::= CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin1",21, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // fin2 ::= COMA par2 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin2",22, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 111: // fin2 ::= CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin2",22, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 112: // fin4 ::= COMA par4 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin4",23, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 113: // fin4 ::= CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin4",23, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 114: // fin6 ::= COMA par6 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin6",24, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 115: // fin6 ::= CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin6",24, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 116: // fin7 ::= COMA par7 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin7",25, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-1)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 117: // fin7 ::= CORCHD CORCHCUADD CORCHD sig3 
            {
              Object RESULT =null;

              CUP$ParserIndigo$result = parser.getSymbolFactory().newSymbol("fin7",25, ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.elementAt(CUP$ParserIndigo$top-3)), ((java_cup.runtime.Symbol)CUP$ParserIndigo$stack.peek()), RESULT);
            }
          return CUP$ParserIndigo$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserIndigo$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserIndigo$do_action(
    int                        CUP$ParserIndigo$act_num,
    java_cup.runtime.lr_parser CUP$ParserIndigo$parser,
    java.util.Stack            CUP$ParserIndigo$stack,
    int                        CUP$ParserIndigo$top)
    throws java.lang.Exception
    {
              return CUP$ParserIndigo$do_action_part00000000(
                               CUP$ParserIndigo$act_num,
                               CUP$ParserIndigo$parser,
                               CUP$ParserIndigo$stack,
                               CUP$ParserIndigo$top);
    }
}

}
