
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symU {
  /* terminals */
  public static final int COMA = 5;
  public static final int USUARIO = 9;
  public static final int EOF = 0;
  public static final int CORCHI = 3;
  public static final int INI = 8;
  public static final int PARI = 6;
  public static final int error = 1;
  public static final int CORCHD = 4;
  public static final int FECHA_CREA = 11;
  public static final int PASS = 10;
  public static final int DOSPUNT = 2;
  public static final int PARD = 7;
  public static final int NOMBREP = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNT",
  "CORCHI",
  "CORCHD",
  "COMA",
  "PARI",
  "PARD",
  "INI",
  "USUARIO",
  "PASS",
  "FECHA_CREA",
  "NOMBREP"
  };
}

